"""update

Revision ID: 5947e4ed42db
Revises: d37b76a689c1
Create Date: 2022-10-01 16:52:06.752039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5947e4ed42db'
down_revision = 'd37b76a689c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vadmin_auth_role', sa.Column('order', sa.Integer(), nullable=True, comment='排序'))
    op.drop_column('vadmin_auth_role', 'index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vadmin_auth_role', sa.Column('index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='排序'))
    op.drop_column('vadmin_auth_role', 'order')
    # ### end Alembic commands ###
