"""update

Revision ID: 5e629ba5c3c8
Revises: 65797098992b
Create Date: 2022-08-08 17:25:54.291997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e629ba5c3c8'
down_revision = '65797098992b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vadmin_record_login',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('telephone', sa.String(length=50), nullable=False, comment='手机号'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='是否登录成功'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='登陆地址'),
    sa.Column('address', sa.String(length=50), nullable=True, comment='登陆地点'),
    sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
    sa.Column('system', sa.String(length=50), nullable=True, comment='操作系统'),
    sa.Column('response', sa.TEXT(), nullable=True, comment='响应信息'),
    sa.Column('request', sa.TEXT(), nullable=True, comment='请求信息'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录记录表'
    )
    op.create_index(op.f('ix_vadmin_record_login_id'), 'vadmin_record_login', ['id'], unique=True)
    op.create_index(op.f('ix_vadmin_record_login_telephone'), 'vadmin_record_login', ['telephone'], unique=False)
    op.create_table('vadmin_record_operation',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('user', sa.Integer(), nullable=True, comment='操作人'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='操作结果状态'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='登陆地址'),
    sa.Column('address', sa.String(length=50), nullable=True, comment='登陆地点'),
    sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
    sa.Column('system', sa.String(length=50), nullable=True, comment='操作系统'),
    sa.Column('response', sa.TEXT(), nullable=True, comment='响应信息'),
    sa.Column('request', sa.TEXT(), nullable=True, comment='请求信息'),
    sa.Column('request_api', sa.String(length=255), nullable=True, comment='请求接口'),
    sa.Column('request_method', sa.String(length=255), nullable=True, comment='请求方式'),
    sa.ForeignKeyConstraint(['user'], ['vadmin_auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='操作记录表'
    )
    op.create_index(op.f('ix_vadmin_record_operation_id'), 'vadmin_record_operation', ['id'], unique=True)
    op.create_table('vadmin_record_sms_send',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作人'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='发送状态'),
    sa.Column('content', sa.String(length=255), nullable=True, comment='发送内容'),
    sa.Column('telephone', sa.String(length=11), nullable=True, comment='目标手机号'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='失败描述'),
    sa.Column('scene', sa.String(length=50), nullable=True, comment='发送场景'),
    sa.ForeignKeyConstraint(['user_id'], ['vadmin_auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='短信发送记录表'
    )
    op.create_index(op.f('ix_vadmin_record_sms_send_id'), 'vadmin_record_sms_send', ['id'], unique=True)
    op.add_column('vadmin_auth_menu', sa.Column('order', sa.Integer(), nullable=True, comment='排序'))
    op.drop_column('vadmin_auth_menu', 'order_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vadmin_auth_menu', sa.Column('order_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='排序'))
    op.drop_column('vadmin_auth_menu', 'order')
    op.drop_index(op.f('ix_vadmin_record_sms_send_id'), table_name='vadmin_record_sms_send')
    op.drop_table('vadmin_record_sms_send')
    op.drop_index(op.f('ix_vadmin_record_operation_id'), table_name='vadmin_record_operation')
    op.drop_table('vadmin_record_operation')
    op.drop_index(op.f('ix_vadmin_record_login_telephone'), table_name='vadmin_record_login')
    op.drop_index(op.f('ix_vadmin_record_login_id'), table_name='vadmin_record_login')
    op.drop_table('vadmin_record_login')
    # ### end Alembic commands ###
