"""update

Revision ID: 65797098992b
Revises: f2390b45da1d
Create Date: 2022-08-08 15:13:27.266162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65797098992b'
down_revision = 'f2390b45da1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vadmin_auth_menu',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='菜单图标'),
    sa.Column('component', sa.String(length=50), nullable=True, comment='前端组件地址'),
    sa.Column('path', sa.String(length=50), nullable=True, comment='前端路由地址'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='是否可用'),
    sa.Column('hidden', sa.Boolean(), nullable=True, comment='是否显示'),
    sa.Column('order_num', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('menu_type', sa.String(length=8), nullable=True, comment='菜单类型'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜单'),
    sa.Column('perms', sa.String(length=50), nullable=True, comment='权限标识'),
    sa.ForeignKeyConstraint(['parent_id'], ['vadmin_auth_menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单表'
    )
    op.create_index(op.f('ix_vadmin_auth_menu_id'), 'vadmin_auth_menu', ['id'], unique=True)
    op.create_index(op.f('ix_vadmin_auth_menu_perms'), 'vadmin_auth_menu', ['perms'], unique=False)
    op.create_index(op.f('ix_vadmin_auth_menu_title'), 'vadmin_auth_menu', ['title'], unique=False)
    op.create_table('vadmin_auth_role',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('role_key', sa.String(length=50), nullable=False, comment='权限字符'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否可用'),
    sa.Column('index', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='是否为超级角色'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表'
    )
    op.create_index(op.f('ix_vadmin_auth_role_id'), 'vadmin_auth_role', ['id'], unique=True)
    op.create_index(op.f('ix_vadmin_auth_role_name'), 'vadmin_auth_role', ['name'], unique=False)
    op.create_index(op.f('ix_vadmin_auth_role_role_key'), 'vadmin_auth_role', ['role_key'], unique=False)
    op.create_table('vadmin_auth_role_menus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['vadmin_auth_menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['vadmin_auth_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'role_id', 'menu_id')
    )
    op.create_index(op.f('ix_vadmin_auth_role_menus_id'), 'vadmin_auth_role_menus', ['id'], unique=True)
    op.create_table('vadmin_auth_user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['vadmin_auth_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['vadmin_auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_id', 'role_id')
    )
    op.create_index(op.f('ix_vadmin_auth_user_roles_id'), 'vadmin_auth_user_roles', ['id'], unique=True)
    op.add_column('vadmin_auth_user', sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像'))
    op.add_column('vadmin_auth_user', sa.Column('gender', sa.String(length=8), nullable=True, comment='性别'))
    op.add_column('vadmin_auth_user', sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否可用'))
    op.add_column('vadmin_auth_user', sa.Column('is_cancel', sa.Boolean(), nullable=True, comment='是否注销'))
    op.add_column('vadmin_auth_user', sa.Column('is_reset_password', sa.Boolean(), nullable=True, comment='是否已经重置密码，没有重置的，登陆系统后必须重置密码'))
    op.add_column('vadmin_auth_user', sa.Column('last_ip', sa.String(length=50), nullable=True, comment='最后一次登录IP'))
    op.add_column('vadmin_auth_user', sa.Column('last_login', sa.DateTime(), nullable=True, comment='最近一次登录时间'))
    op.drop_column('vadmin_auth_user', 'wechat')
    op.drop_column('vadmin_auth_user', 'qq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vadmin_auth_user', sa.Column('qq', mysql.VARCHAR(length=50), nullable=True, comment='QQ'))
    op.add_column('vadmin_auth_user', sa.Column('wechat', mysql.VARCHAR(length=50), nullable=True, comment='微信'))
    op.drop_column('vadmin_auth_user', 'last_login')
    op.drop_column('vadmin_auth_user', 'last_ip')
    op.drop_column('vadmin_auth_user', 'is_reset_password')
    op.drop_column('vadmin_auth_user', 'is_cancel')
    op.drop_column('vadmin_auth_user', 'is_active')
    op.drop_column('vadmin_auth_user', 'gender')
    op.drop_column('vadmin_auth_user', 'avatar')
    op.drop_index(op.f('ix_vadmin_auth_user_roles_id'), table_name='vadmin_auth_user_roles')
    op.drop_table('vadmin_auth_user_roles')
    op.drop_index(op.f('ix_vadmin_auth_role_menus_id'), table_name='vadmin_auth_role_menus')
    op.drop_table('vadmin_auth_role_menus')
    op.drop_index(op.f('ix_vadmin_auth_role_role_key'), table_name='vadmin_auth_role')
    op.drop_index(op.f('ix_vadmin_auth_role_name'), table_name='vadmin_auth_role')
    op.drop_index(op.f('ix_vadmin_auth_role_id'), table_name='vadmin_auth_role')
    op.drop_table('vadmin_auth_role')
    op.drop_index(op.f('ix_vadmin_auth_menu_title'), table_name='vadmin_auth_menu')
    op.drop_index(op.f('ix_vadmin_auth_menu_perms'), table_name='vadmin_auth_menu')
    op.drop_index(op.f('ix_vadmin_auth_menu_id'), table_name='vadmin_auth_menu')
    op.drop_table('vadmin_auth_menu')
    # ### end Alembic commands ###
