"""update

Revision ID: ab5fb033599e
Revises: 5947e4ed42db
Create Date: 2022-10-02 22:40:45.967326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab5fb033599e'
down_revision = '5947e4ed42db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vadmin_auth_role', sa.Column('disabled', sa.Boolean(), nullable=True, comment='是否禁用'))
    op.drop_column('vadmin_auth_role', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vadmin_auth_role', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否可用'))
    op.drop_column('vadmin_auth_role', 'disabled')
    # ### end Alembic commands ###
