"""更新迁移文件

Revision ID: bc1417d96581
Revises: a95a845d335f
Create Date: 2022-07-06 21:56:41.154567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1417d96581'
down_revision = 'a95a845d335f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vadmin_auth_user',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('telephone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='姓名'),
    sa.Column('nickname', sa.String(length=20), nullable=True, comment='昵称'),
    sa.Column('wechat', sa.String(length=50), nullable=True, comment='微信'),
    sa.Column('qq', sa.String(length=50), nullable=True, comment='QQ'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='密码'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_vadmin_auth_user_id'), 'vadmin_auth_user', ['id'], unique=True)
    op.create_index(op.f('ix_vadmin_auth_user_name'), 'vadmin_auth_user', ['name'], unique=False)
    op.create_index(op.f('ix_vadmin_auth_user_telephone'), 'vadmin_auth_user', ['telephone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vadmin_auth_user_telephone'), table_name='vadmin_auth_user')
    op.drop_index(op.f('ix_vadmin_auth_user_name'), table_name='vadmin_auth_user')
    op.drop_index(op.f('ix_vadmin_auth_user_id'), table_name='vadmin_auth_user')
    op.drop_table('vadmin_auth_user')
    # ### end Alembic commands ###
