"""update

Revision ID: d37b76a689c1
Revises: 2d8939b3a228
Create Date: 2022-09-22 16:35:48.607099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd37b76a689c1'
down_revision = '2d8939b3a228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vadmin_auth_menu', sa.Column('title', sa.String(length=50), nullable=False, comment='名称'))
    op.drop_index('ix_vadmin_auth_menu_name', table_name='vadmin_auth_menu')
    op.create_index(op.f('ix_vadmin_auth_menu_title'), 'vadmin_auth_menu', ['title'], unique=False)
    op.drop_column('vadmin_auth_menu', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vadmin_auth_menu', sa.Column('name', mysql.VARCHAR(length=50), nullable=False, comment='名称'))
    op.drop_index(op.f('ix_vadmin_auth_menu_title'), table_name='vadmin_auth_menu')
    op.create_index('ix_vadmin_auth_menu_name', 'vadmin_auth_menu', ['name'], unique=False)
    op.drop_column('vadmin_auth_menu', 'title')
    # ### end Alembic commands ###
