"""update

Revision ID: d4898760c577
Revises: 03e55ed3e858
Create Date: 2022-08-13 11:40:09.131602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4898760c577'
down_revision = '03e55ed3e858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vadmin_auth_menu', sa.Column('redirect', sa.String(length=100), nullable=True, comment='重定向地址'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vadmin_auth_menu', 'redirect')
    # ### end Alembic commands ###
