"""update

Revision ID: f2390b45da1d
Revises: 0cd7a858c5a5
Create Date: 2022-08-08 13:36:03.625827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2390b45da1d'
down_revision = '0cd7a858c5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
